[phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[phases.build]
cmds = ["cd backend && mvn clean package -DskipTests -q"]

[start]
cmd = "java -jar backend/target/dealership-api-0.0.1-SNAPSHOT.jar"
